// Need Username, githubname, Join date, Bio, Repos count, Followers count, following count, location, twitter handle, Website, company

export const mockData = {
  "login": "Xz15t",
  "id": 76773948,
  "node_id": "MDQ6VXNlcjc2NzczOTQ4",
  "avatar_url": "https://avatars.githubusercontent.com/u/76773948?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Xz15t",
  "html_url": "https://github.com/Xz15t",
  "followers_url": "https://api.github.com/users/Xz15t/followers",
  "following_url": "https://api.github.com/users/Xz15t/following{/other_user}",
  "gists_url": "https://api.github.com/users/Xz15t/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Xz15t/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Xz15t/subscriptions",
  "organizations_url": "https://api.github.com/users/Xz15t/orgs",
  "repos_url": "https://api.github.com/users/Xz15t/repos",
  "events_url": "https://api.github.com/users/Xz15t/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Xz15t/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mukund Mohan Zutshi",
  "company": null,
  "blog": "",
  "location": "Kanpur",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 2,
  "following": 1,
  "created_at": "2020-12-30T10:12:42Z",
  "updated_at": "2022-04-14T04:20:27Z"
  }